apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend-delivery-service
  name: backend-delivery-service
spec:
  ports:
    - port: 8072
      protocol: TCP
      targetPort: 8072
  selector:
    app: backend-delivery-service
status:
  loadBalancer: {}