apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-delivery
  name: ctse-delivery
spec:
  ports:
    - port: 8072
      protocol: TCP
      targetPort: 8072
  selector:
    app: ctse-delivery
status:
  loadBalancer: {}